######################################################################
# Automatically generated by qmake (3.0) ?? 7? 19 17:06:56 2013
######################################################################

TEMPLATE = app
TARGET = helloworld
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp
